[package]
name = "prototype"
version = "0.1.0"
authors = ["Rahul Butani <rr.butani@gmail.com>"]
edition = "2018"
# default-run = "tui"

[dependencies]
prost = "0.5"
bytes = "0.4"
futures="0.1"
rand = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-serial = "3.3"
tm4c123x-hal = "0.9.2"


[features]

shims = []

[dev-dependencies]
tui = "0.6.2"


[[example]]
name = "tui"
path = "examples/tui/main.rs"
required-features = ["shims"]

[build-dependencies]
prost-build = { version = "0.4"  }
